#!/usr/bin/env node
// Portable quality gate for a PRODUCT repo. Copy to scripts/quality-gate.mjs and wire `npm run gate`.
// Checks the structural rules from build-standard/SCHEME.md that do not need product knowledge:
//   authority table exists · STATUS is generated and fresh · open S1 · expired waivers ·
//   no doc claiming to be the one moving "latest" · no bare credentials in docs.
//
// Exit 1 on blocking failure. Safe to run in CI before tests.

import { readFile, readdir, stat } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const ROOT = process.env.GATE_ROOT ?? process.cwd();
const fails = [];
const warns = [];
const notes = [];

const read = async (p) => readFile(join(ROOT, p), 'utf8');
const exists = async (p) => { try { await stat(join(ROOT, p)); return true; } catch { return false; } };

// --- DOC-1 authority table ------------------------------------------------
const authority = ['product/README.md', 'docs/README.md'];
const authorityFile = (await Promise.all(authority.map(async (p) => ((await exists(p)) ? p : null)))).find(Boolean);
if (!authorityFile) {
  fails.push('DOC-1: no authority table (expected product/README.md)');
} else {
  const text = await read(authorityFile);
  if (!/L[0-3]\b/.test(text)) warns.push(`DOC-1: ${authorityFile} does not declare a maturity level (L0..L3)`);
  notes.push(`authority: ${authorityFile}`);
}

// --- DOC-2 STATUS is generated -------------------------------------------
if (!(await exists('STATUS.md'))) {
  fails.push('DOC-2: STATUS.md missing — add a generator, even a minimal one');
} else {
  const status = await read('STATUS.md');
  if (!/generated|Generated|生成/.test(status)) fails.push('DOC-2: STATUS.md lacks a generated banner');
  if (/^\s*\|?\s*\d{1,3}\s*%/m.test(status) && !/Generated by/.test(status)) {
    warns.push('DOC-2: STATUS.md looks hand-written (percentages without generator banner)');
  }
}

// --- COMPOUND-5 open S1 ---------------------------------------------------
if (await exists('product/risks.md')) {
  const risks = await read('product/risks.md');
  const openS1 = risks
    .split('\n')
    .filter((l) => l.startsWith('|') && /\bS1\b/.test(l) && /\bopen\b/.test(l)).length;
  notes.push(`open S1: ${openS1}`);
  if (openS1 > 0) fails.push(`COMPOUND-5: ${openS1} open S1 — official release blocked (beta channel only)`);
} else {
  warns.push('COMPOUND-5: product/risks.md missing — cannot evaluate S1');
}

// --- waivers must not be expired -----------------------------------------
if (await exists('product/waivers.md')) {
  const today = new Date().toISOString().slice(0, 10);
  for (const line of (await read('product/waivers.md')).split('\n')) {
    if (!line.startsWith('|')) continue;
    const cells = line.split('|').map((c) => c.trim());
    const id = cells[1];
    const due = cells.find((c) => /^\d{4}-\d{2}-\d{2}$/.test(c));
    if (!/^[A-Z]+-\d+$/.test(id ?? '')) continue;
    if (!due) { fails.push(`WAIVER: ${id} has no due date`); continue; }
    if (due < today) fails.push(`WAIVER: ${id} expired on ${due} — the gate is failing again`);
    if (/^(LAUNCH-5|PRESHIP-4)$/.test(id)) fails.push(`WAIVER: ${id} is not waivable`);
  }
}

// --- DOC-5 no moving "latest" doc, DOC-4 archive exists -------------------
async function walk(dir = '.', acc = []) {
  for (const e of await readdir(join(ROOT, dir), { withFileTypes: true })) {
    if (e.name.startsWith('.') || ['node_modules', 'target', 'dist', 'build'].includes(e.name)) continue;
    const rel = dir === '.' ? e.name : `${dir}/${e.name}`;
    if (e.isDirectory()) await walk(rel, acc);
    else if (e.name.endsWith('.md')) acc.push(rel);
  }
  return acc;
}
const docs = await walk();
for (const f of docs) {
  if (f.includes('archive/')) continue;
  if (/最新|latest-version/i.test(f)) fails.push(`DOC-5: living doc claims to be the moving latest -> ${f}`);
  const text = await read(f);
  if (/\b(sk-[A-Za-z0-9]{16,}|ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{12,})\b/.test(text)) {
    fails.push(`SECRET: credential-shaped string in ${f}`);
  }
  if (/(密码|password)\s*[:：]\s*\S+/i.test(text)) warns.push(`SECRET: ${f} may contain a password`);
}
notes.push(`markdown scanned: ${docs.length}`);

// --- report ---------------------------------------------------------------
console.log(`quality gate — ${resolve(ROOT)}`);
for (const n of notes) console.log(`  · ${n}`);
for (const w of warns) console.log(`  warn  ${w}`);
for (const f of fails) console.log(`  FAIL  ${f}`);

if (fails.length) {
  console.log(`\n${fails.length} blocking problem(s). Fix, or file a waiver with a due date in product/waivers.md.`);
  process.exit(1);
}
console.log(`\nstructural gates green${warns.length ? ` (${warns.length} warning)` : ''}.`);
