#!/usr/bin/env node
// Self-check for this standard repo. A standard that cannot check itself is a wish.
// Usage: node checks/check.mjs

import { readFile, readdir, stat } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const run = promisify(execFile);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const failures = [];
const warnings = [];
const fail = (code, msg) => failures.push(`${code}: ${msg}`);
const warn = (code, msg) => warnings.push(`${code}: ${msg}`);

const read = (p) => readFile(join(ROOT, p), 'utf8');

// Gate id prefixes owned by ship-standard. Keep in sync when a dimension is added there.
const SHIP_PREFIXES = new Set([
  'LAUNCH', 'RESIL', 'DIAG', 'KERNEL', 'PATH', 'PRESHIP', 'COMPOUND', 'PROBE', 'DOC',
]);

async function listMarkdown(dir = '.', acc = []) {
  for (const e of await readdir(join(ROOT, dir), { withFileTypes: true })) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const rel = dir === '.' ? e.name : `${dir}/${e.name}`;
    if (e.isDirectory()) await listMarkdown(rel, acc);
    else if (e.name.endsWith('.md')) acc.push(rel);
  }
  return acc;
}

// --- catalog ↔ files ------------------------------------------------------
const catalog = JSON.parse(await read('catalog.json'));
for (const p of catalog.practices) {
  try {
    await stat(join(ROOT, p.path));
  } catch {
    fail('CATALOG-MISSING', `catalog lists ${p.path} but the file does not exist`);
  }
}
try {
  await stat(join(ROOT, catalog.scheme));
} catch {
  fail('CATALOG-MISSING', `catalog.scheme points at missing ${catalog.scheme}`);
}

// --- SCHEME must keep its load-bearing parts ------------------------------
const scheme = await read('SCHEME.md');
const lawsSection = scheme.split('## 3. 十条铁律')[1]?.split('\n## ')[0] ?? '';
const laws = lawsSection.match(/^\d+\. \*\*/gm) ?? [];
if (laws.length !== 10) fail('SCHEME-LAWS', `expected 10 iron rules in §3, found ${laws.length}`);
for (const level of ['L0', 'L1', 'L2', 'L3']) {
  if (!scheme.includes(`**${level} `)) fail('SCHEME-MATURITY', `maturity level ${level} is missing`);
}
for (const section of ['## 6. 豁免机制', '## 11. 明确不适用', '## 1. 因果模型']) {
  if (!scheme.includes(section)) fail('SCHEME-SECTION', `SCHEME.md is missing "${section}"`);
}
if (!/ship-standard/.test(scheme)) fail('SCHEME-BOUNDARY', 'SCHEME.md must point acceptance at ship-standard');

// --- every referenced gate id must look like a ship-standard id -----------
const mdFiles = await listMarkdown();
for (const f of mdFiles) {
  const text = await read(f);
  for (const m of text.matchAll(/`([A-Z]{3,}-\d+)`/g)) {
    const prefix = m[1].split('-')[0];
    if (!SHIP_PREFIXES.has(prefix)) {
      fail('GATE-UNKNOWN', `${f}: gate id ${m[1]} has no matching ship-standard dimension`);
    }
  }
}

// --- doc-system rules applied to ourselves --------------------------------
for (const f of mdFiles) {
  if (/最新|latest-version|FINAL/i.test(f)) fail('DOC-5', `file name claims a moving target: ${f}`);
  const text = await read(f);

  const headings = text.split('\n').filter((l) => /^##\s+\S/.test(l)).map((l) => l.trim());
  const dupes = [...new Set(headings.filter((h, i) => headings.indexOf(h) !== i))];
  if (dupes.length) fail('DOC-DUP-HEADING', `${f}: repeated heading ${dupes.join(', ')}`);

  for (const m of text.matchAll(/\[[^\]]*\]\((\.\.?\/[^)#\s]+)/g)) {
    // templates/ are meant to be copied into a product repo, so their `./x` links
    // resolve there, not here. Only their `../` links point back at this repo.
    if (f.startsWith('templates/') && m[1].startsWith('./')) continue;
    try {
      await stat(resolve(dirname(join(ROOT, f)), m[1]));
    } catch {
      fail('LINK-DEAD', `${f}: dead relative link ${m[1]}`);
    }
  }

  if (/\b(sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{12,}|ghp_[A-Za-z0-9]{20,})\b/.test(text)) {
    fail('SECRET', `${f}: looks like a credential`);
  }
  if (/\b\d{1,3}(\.\d{1,3}){3}\b/.test(text) && !/0\.0\.0\.0|127\.0\.0\.1/.test(text)) {
    warn('HOST-IN-DOC', `${f}: contains a bare IP address`);
  }
}

// --- the portable gate we ship must at least parse ------------------------
try {
  await run(process.execPath, ['--check', join(ROOT, 'templates/quality-gate.mjs')]);
} catch (err) {
  fail('TEMPLATE-BROKEN', `templates/quality-gate.mjs does not parse: ${err.stderr ?? err.message}`);
}

// --- STATUS must be generated --------------------------------------------
try {
  const status = await read('STATUS.md');
  if (!/Generated by/.test(status)) fail('DOC-2', 'STATUS.md is missing the generated banner');
  if (!status.includes(catalog.version)) {
    fail('DOC-2', `STATUS.md does not show catalog version ${catalog.version} — run npm run status`);
  }
} catch {
  fail('DOC-2', 'STATUS.md is missing — run npm run status');
}

// --- report --------------------------------------------------------------
console.log('build-standard self-check');
console.log(`  practices: ${catalog.practices.length}`);
console.log(`  iron rules: ${laws.length}`);
console.log(`  markdown:  ${mdFiles.length}`);
for (const w of warnings) console.log(`  warn  ${w}`);
for (const f of failures) console.log(`  FAIL  ${f}`);

if (failures.length) {
  console.log(`\n${failures.length} blocking problem(s).`);
  process.exit(1);
}
console.log(`\nall gates green${warnings.length ? ` (${warnings.length} warning)` : ''}.`);
