#!/usr/bin/env node
// Generates STATUS.md from catalog.json + SCHEME.md. Never hand-edit STATUS.md.

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFile(join(ROOT, p), 'utf8');

const catalog = JSON.parse(await read('catalog.json'));
const pinned = JSON.parse(await read('checks/gates.pinned.json'));
const scheme = await read('SCHEME.md');
const section = (h) => scheme.split(h)[1]?.split('\n## ')[0] ?? '';

const lawsSection = section('## 3. 十二条铁律');
const laws = (lawsSection.match(/^\d+\. \*\*(.+?)\*\*（([\d、]+)）/gm) ?? []).map((l) => {
  const m = l.match(/^\d+\. \*\*(.+?)\*\*（([\d、]+)）/);
  return { text: m[1], leaks: m[2] };
});
const leakCount = (section('## 1. 因果模型').match(/^\| \*\*\d+\*\* \|/gm) ?? []).length;

const templates = (await readdir(join(ROOT, 'templates'))).filter((f) => f !== 'README.md').sort();
const practiceRows = catalog.practices
  .map((p) => `| [${p.id}](${p.path}) | ${p.title} | ${p.status} |`)
  .join('\n');

const levelRows = Object.entries(pinned.levels)
  .map(([level, def]) => {
    const n = pinned.gates.filter(
      (g) => !g.deprecated
        && def.stages.includes(g.stage)
        && g.severity === 'block'
        && pinned.applies[g.dimension] === 'all',
    ).length;
    return `| **${level} ${def.name}** | ${def.stages.map((s) => `\`${s}\``).join(' ')} | ${n} |`;
  })
  .join('\n');

const out = `# STATUS

> Generated by \`checks/render-status.mjs\`. Do not edit by hand — change \`catalog.json\` / \`SCHEME.md\` / the practice docs instead.

Standard version: \`${catalog.version}\` · gates pinned at ship-standard \`${pinned.version}\`

## Scheme

- 总纲：[SCHEME.md](SCHEME.md) — ${leakCount} 个泄漏推出 ${laws.length} 条铁律
- 落地顺序：[ADOPTION.md](ADOPTION.md)
- 上线判定：[ship-standard](${catalog.related['ship-standard']})
- 洞察落成定律：[creativity-is-engineering](${catalog.related['creativity-is-engineering']})

铁律清单（括号是它堵的泄漏）：

${laws.map((l, i) => `${i + 1}. ${l.text}（${l.leaks}）`).join('\n')}

## 成熟度（由 stage 推导，本页不手写清单）

| 级别 | 覆盖 stage | 阻断门禁数（通用纬度） |
|------|------------|------------------------|
${levelRows}

opt-in 纬度（${Object.entries(pinned.applies).filter(([, v]) => v === 'opt-in').map(([k]) => k).join('、')}）只有产品声明了才绑定。
不可豁免：${pinned.nonWaivable.map((i) => `\`${i}\``).join(' ')} —— 这一组在任何级别都阻断。

## Practices

| id | 一句话 | 状态 |
|----|--------|------|
${practiceRows}

## Templates（复制进产品仓）

${templates.map((t) => `- [\`${t}\`](templates/${t})`).join('\n')}

## 本仓自己过了什么

\`npm run verify\` 会跑：铁律条数与泄漏标注、§4 是否偷偷手写门禁 id、§5 是否重抄七步表、
每个门禁 id 是否真实存在于钉住的 \`gates.json\`、死链、重复标题、清单漂移，
以及**把 \`templates/quality-gate.mjs\` 真的跑在 3 个 fixture 仓上**（绿 / 红 / 带豁免）。

## How to use

- 先读 SCHEME.md，再按 ADOPTION.md 落地，最后用 ship-standard 的门禁 id 判定能不能发。
- 引用门禁请用 id（例如 \`PATH-3\`）；过不了写 \`product/waivers.md\`，必须带到期日与 owner。
`;

await writeFile(join(ROOT, 'STATUS.md'), out);
console.log(`wrote STATUS.md (${catalog.practices.length} practices, ${laws.length} laws, ${leakCount} leaks, version ${catalog.version})`);
