#!/usr/bin/env node
// Generates STATUS.md from catalog.json + SCHEME.md. Never hand-edit STATUS.md.

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFile(join(ROOT, p), 'utf8');

const catalog = JSON.parse(await read('catalog.json'));
const scheme = await read('SCHEME.md');

const lawsSection = scheme.split('## 3. 十条铁律')[1]?.split('\n## ')[0] ?? '';
const laws = (lawsSection.match(/^\d+\. \*\*(.+?)\*\*/gm) ?? []).map((l) =>
  l.replace(/^\d+\. \*\*/, '').replace(/\*\*$/, ''),
);
const templates = (await readdir(join(ROOT, 'templates'))).filter((f) => f !== 'README.md').sort();

const practiceRows = catalog.practices
  .map((p) => `| [${p.id}](${p.path}) | ${p.title} | ${p.status} |`)
  .join('\n');

const out = `# STATUS

> Generated by \`checks/render-status.mjs\`. Do not edit by hand — change \`catalog.json\` / \`SCHEME.md\` / the practice docs instead.

Standard version: \`${catalog.version}\`

## Scheme

- 总纲：[SCHEME.md](./SCHEME.md)（${laws.length} 条铁律）
- 落地顺序：[ADOPTION.md](./ADOPTION.md)
- 上线判定：[ship-standard](${catalog.related['ship-standard']})

铁律清单：

${laws.map((l, i) => `${i + 1}. ${l}`).join('\n')}

## Practices

| id | 一句话 | 状态 |
|----|--------|------|
${practiceRows}

## Templates（复制进产品仓）

${templates.map((t) => `- [\`${t}\`](./templates/${t})`).join('\n')}

## How to use

- 先读 SCHEME.md，再按 ADOPTION.md 落地，最后用 ship-standard 的门禁 id 判定能不能发。
- 引用门禁请用 id（例如 \`PATH-3\`）；过不了写 \`product/waivers.md\`，必须带到期日。
`;

await writeFile(join(ROOT, 'STATUS.md'), out);
console.log(`wrote STATUS.md (${catalog.practices.length} practices, ${laws.length} laws, version ${catalog.version})`);
